-- Prosody config — Server A (federation target "server-a.local")
-- TASK-13 (specs/13-jabber-design.md §4.2)
--
-- DEV-ONLY — ships with plain-text auth and s2s_secure_auth disabled so the
-- hackathon Docker federation can handshake without a real CA. Do NOT deploy
-- this to anything exposed to the public internet.

admins = { "admin@server-a.local" }

-- Module search path: built-ins from the image + the custom webhook shim we
-- mount under /usr/lib/prosody/modules-custom.
plugin_paths = { "/usr/lib/prosody/modules-custom" }

modules_enabled = {
  "roster";       -- Roster (contact list) support
  "saslauth";     -- SASL authentication
  "tls";          -- TLS on c2s (STARTTLS)
  "dialback";     -- S2S dialback (required for federation with non-cert peers)
  "carbons";      -- Message carbons (XEP-0280)
  "mam";          -- Message archive (XEP-0313) — not bridged to FastAPI (v2)
  "http";         -- HTTP listener (required for mod_http_api)
  "posix";        -- PID file, syslog, etc.
  "disco";        -- Service discovery
  "version";      -- Respond to version queries
  "ping";         -- XEP-0199 client+server pings
  -- "smacks" (XEP-0198) intentionally omitted: not bundled in
  -- prosody/prosody:0.11.9 and pulling it from prosody-modules would add a
  -- build step for a feature we don't demonstrate.
  "fastapi_webhook"; -- TASK-13: posts federation + session events to FastAPI
  "admin_api";       -- TASK-13: FastAPI -> Prosody user provisioning
}

modules_disabled = {}

-- Allow registration via HTTP API only; in-band registration is off so the
-- FastAPI app remains the source of truth for account creation.
allow_registration = false

-- c2s TLS: self-signed cert is generated by the image on first boot; see
-- /var/lib/prosody when debugging.
c2s_require_encryption = false  -- dev: let plaintext clients connect on 5222

-- S2S settings — federation bus.
s2s_secure_auth = false  -- DEV ONLY: accept dialback without valid cert chain
s2s_require_encryption = false
s2s_insecure_domains = { "server-b.local" }

authentication = "internal_plain"  -- DEV ONLY — passwords stored as plaintext
                                   -- so the FastAPI bridge can "create_user"
                                   -- with the raw password it already has.

log = {
  { levels = { min = "info" }, to = "console" };
}

-- HTTP admin API (mod_http_api is not built-in for 0.12 — we rely on the
-- prosody-modules community repo mounted into modules-custom. For the
-- hackathon we ship prosodyctl-style admin via the image's default admin
-- telnet, but expose a plain HTTP listener so the backend can probe liveness
-- and future webhook modules have somewhere to attach.)
http_ports = { 5280 }
https_ports = {}  -- dev-only: no cert, no TLS variant. Quiets a startup warning.
http_interfaces = { "*" }
-- Accept requests whose Host header is the Docker service name. Required for
-- the per-vhost mod_admin_api routes to dispatch correctly — see the
-- prosody_single.cfg.lua comment.
http_external_url = "http://prosody_a:5280/"
http_host = "prosody_a"
-- Trust the docker internal networks. 172.16.0.0/12 covers default compose
-- bridge ranges; 10.0.0.0/8 covers Rancher/Podman. Plus localhost for probes.
trusted_proxies = { "127.0.0.1", "::1", "172.16.0.0/12", "10.0.0.0/8" }

-- mod_http_api bearer token. Prosody's community module reads this via
-- the module-scope `api_auth_token` option in prosody.cfg.lua rather than
-- from the environment (Lua config can't os.getenv the value safely without
-- a wrapper), so for the hackathon we bake a dev token here. In production
-- this value should be regenerated per deployment.
api_auth_token = "dev-admin-token"

-- FastAPI webhook target — read by the (future) mod_fastapi_webhook Lua
-- module; harmless to leave defined here even if the module isn't loaded.
fastapi_webhook_url = "http://backend:8000/api/internal/xmpp/event"
fastapi_webhook_token = "dev-webhook-token"

VirtualHost "server-a.local"
  enabled = true
