"""add is_admin and federation_log (TASK-13)

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-04-21 02:00:00.000000
"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 — required by autogenerated column type references
from alembic import op

revision: str = "b2c3d4e5f6a7"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "user",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.create_table(
        "federation_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("direction", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("local_jid", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("remote_jid", sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
        sa.Column("remote_server", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("message_preview", sqlmodel.sql.sqltypes.AutoString(length=140), nullable=True),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_federation_log_ts"), "federation_log", ["ts"])
    op.create_index(op.f("ix_federation_log_remote_server"), "federation_log", ["remote_server"])
    op.create_index(op.f("ix_federation_log_session_id"), "federation_log", ["session_id"])


def downgrade() -> None:
    op.drop_index(op.f("ix_federation_log_session_id"), table_name="federation_log")
    op.drop_index(op.f("ix_federation_log_remote_server"), table_name="federation_log")
    op.drop_index(op.f("ix_federation_log_ts"), table_name="federation_log")
    op.drop_table("federation_log")
    op.drop_column("user", "is_admin")
